services:
  db:
    image: timescale/timescaledb-ha:pg16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./cpu_usage.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:secret@db:5432/homework
      - WORKER_COUNT=4